<?php

/*
* Implements hook_entity_info_alter().
*/
function os2intra_view_modes_entity_info_alter(&$entity_info) {

  // Node view modes
  $entity_info['node']['view modes']['list'] = array(
    'label'           => t('List'),
    'custom settings' => TRUE,
  );

  // User view modes
  $entity_info['user']['view modes']['teaser'] = array(
    'label' => t('User teaser'),
    'custom settings' => TRUE,
  );

  xdebug_break();
}
