<?php

function custom_notification_settings_menu() {
	$items = array();
	$items['custom_notification_settings'] = array(
		'Title' => 'Custom Notification Settings',
		'access callback' => true,
		'access arguments' => array('access content'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('custom_notification_settings_form'),
		'type' => MENU_CALLBACK
	);

	return $items;
}


function custom_notification_settings_form($form, &$form_state) {

	$weekdays = array(
		'mon' => 'Monday',
		'tue' => 'Tuesday',
		'wed' => 'Wednesday',
		'thu' => 'Thursday',
		'fri' => 'Friday',
		'sat' => 'Saturday',
		'sun' => 'Sunday',
	);

	$time = array(
		'00-05' => '00:00 - 05:59',
		'06-11' => '06:00 - 11:59',
		'12-17' => '12:00 - 17:59',
		'18-23' => '18:00 - 23:59',
	);

	$form['markup'] = array(
		'#type' => 'markup',
		'#markup' => '<p>Please specify when you are ready to receive notifications:</p>'
	);

	$i = 1;
	$form['p-1'] = array(
		'#type' => 'markup',
		'#markup' => '<div style="float:left; width:200px;">'
	);

	foreach ($weekdays as $w_key => $w_value) {
		$form['day-' . $w_key . '-title'] = array(
			'#type' => 'markup',
			'#markup' => '<h1>' . $w_value . '</h1>'
		);

		$day_period = array();
		foreach($time as $t_key => $t_value) {
			$day_period[$w_key . '-' . $t_key] = $t_value;
		}

		$form['day-' . $w_key] = array(
			'#type' => 'checkboxes',
			'#options' => $day_period,
			'#default_value' => _custom_notification_settings_get_hours($w_key),
		);

		$form['p-' . ++$i] = array(
			'#type' => 'markup',
			'#markup' => '</div><div style="float:left; width:200px;">'
		);
	}

	$form['p-' . ++$i] = array(
		'#type' => 'markup',
		'#markup' => '</div><div style="clear:both;"></div>'
	);

	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Save changes',
	);

	return $form;
}


/**
 * Validates the form.
 */
function custom_notification_settings_form_validate($form, &$form_state) {
	/* We're not doing anything right now... */
}


/*
 * Form submission
 */
function custom_notification_settings_form_submit($form, &$form_state) {
	drupal_set_message(t('The form has been submitted.'));
	drupal_set_message(t('We don\'t save anything at the moment...'));
}


function _custom_notification_settings_get_hours($k) {
	return array($k . '-12-17', $k . '-18-23');
}

