<?php

function os2intra_email_notification_form_os2intra_settings_settings_form_alter(&$form, &$form_state, $form_id) {

  $form['os2intra_email_notification'] = array(
    '#type' => 'fieldset',
    '#title' => t('Email notification'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['os2intra_email_notification']['os2intra_email_notification_node_insert'] = array(
    '#title' => t('Enable users notification on node insert'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('os2intra_email_notification_node_insert', true),
  );
  $form['os2intra_email_notification']['os2intra_email_notification_node_update'] = array(
    '#title' => t('Enable users notification on node update'),
    '#type' => 'checkbox',
    '#default_value' => variable_get('os2intra_email_notification_node_update', false),
  );
}

/**
 * Implements hook_node_insert() */

function os2intra_email_notification_node_insert($node) { 

    list(,, $bundle) = entity_extract_ids('node', $node);
 if (!og_is_group_content_type('node', $bundle)) {
    return;
  }

  if (variable_get('os2intra_email_notification_node_insert', true) == false) {
    return;
  }
  entity_get_controller('node')->resetCache(array($node->nid));

  
  $message_type = 'os2intra_msgtp_afdelingsindhold';
  $hook = 'node_insert';
  
  
  drupal_alter('os2intra_email_notification_message_selection', $message_type, $hook, $node);
  $account = user_load($node->uid);
  
  
  $message = message_create($message_type, array('uid' => $account->uid, 'timestamp' => $node->created));
  
  
  $wrapper = entity_metadata_wrapper('message', $message); 
  $wrapper->field_target_nodes->set($node);
  $wrapper->field_os2intra_afdindh_afdeling->set($node->og_group_ref['und'][0]['target_id']); 
    
  $options = array( 
    'rendered fields' => array( 
      'message_notify_email_subject' => 'field_os2intra_afdindh_subject', 
      'message_notify_email_body' => 'field_os2intra_afdindh_body', 
    ), 
  ); 
  $subscribe_options = array( 
    'subscribe message' => TRUE, 
    'email message' => TRUE,
    'entity access' => FALSE
  ); 
  if (module_exists('message_subscribe')) { 
    message_subscribe_send_message('node', $node, $message, array('email' => $options), $subscribe_options); 
  } 
}


/**
 * Implements hook_node_update() */
function os2intra_email_notification_node_update($node) {

  list(,, $bundle) = entity_extract_ids('node', $node);
  if (!og_is_group_content_type('node', $bundle)) {
    return;
  }
  if (variable_get('os2intra_groups_node_type') == $bundle) {
   return;
  }

  if (variable_get('os2intra_email_notification_node_update', false) == false) {
    return;
  }
  
  entity_get_controller('node')->resetCache(array($node->nid));


  $message_type = 'os2intra_msgtp_afdelingsindhold_indhold_opdateret';
  $hook = 'node_update';


  drupal_alter('os2intra_email_notification_message_selection', $message_type, $hook, $node);
  $account = user_load($node->uid);


  $message = message_create($message_type, array('uid' => $account->uid, 'timestamp' => $node->created));


  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_target_nodes->set($node);
  $wrapper->field_os2intra_afdindh_afdeling->set($node->og_group_ref['und'][0]['target_id']);

  $options = array(
    'rendered fields' => array(
      'message_notify_email_subject' => 'field_os2intra_afdindh_subject',
      'message_notify_email_body' => 'field_os2intra_afdindh_body',
    ),
  );
  $subscribe_options = array(
    'subscribe message' => TRUE,
    'email message' => TRUE,
    'entity access' => FALSE
  );
  if (module_exists('message_subscribe')) {
    message_subscribe_send_message('node', $node, $message, array('email' => $options), $subscribe_options);
  }
}
