<?php
// ELMS: CKEditor Link OG
// Development Sponsored by The Pennsylvania State University
// ELMS is Copyright (C) 2008-2012  The Pennsylvania State University
//
// Bryan Ollendyke
// bto108@psu.edu
//
// Keith D. Bailey
// kdb163@psu.edu
//
// 12 Borland
// University Park,  PA 16802
/**
 * @file
 * Limit results to only links within the current group
 */

/**
 * Implements hook_ckeditor_link_autocomplete_alter().
 */
function ckeditor_link_og_ckeditor_link_autocomplete_alter(&$results, $string) {
  $results = array();
  // get current node to exclude self linking
  $nid = arg(1);
  // get current group to keep results in context
  $group = $_SESSION['og_context'];
  if ($string !== '') {
    // select anything that's in this group, not this page, and not a book root
    $query = db_select('node', 'n')
      ->fields('n', array('nid', 'title'))
      ->condition('n.nid', $nid, '<>')
      ->condition('og.gid', $group['gid'])
      ->condition('og.entity_type', 'node')
      ->condition('n.title', '%%%s%%', 'like')
      ->orderBy('n.title', 'asc')
      ->orderBy('n.type', 'asc');
    $query->join('og_membership', 'og', 'og.etid = n.nid');
    $result = $query->execute();
    foreach ($result as $node) {
      $results['node/' . $node->nid] = check_plain($node->title);
    }
  }
  return $results;
}
