<?php
/**
 * @file
 * Code for the OS2intra settings feature.
 */

include_once 'os2intra_settings.features.inc';


/**
 * OS2Intra_settings_permission.
 */
function os2intra_settings_permission() {
  return array(
    'administer os2intra' => array(
      'title' => t('Administer OS2Intra'),
      'description' => t('Access settings and administration pages for OS2Intra')
    ),
  );
}

/**
 * Implements hook_menu().
 */
function os2intra_settings_menu() {
  $items = array();
  $items['admin/config/os2intra'] = array(
    'title' => 'OS2Intra Setup',
    'description' => 'Manage OSIntra settings',
    'position' => 'right',
    'weight' => -15,
    'access arguments' => array('administer os2intra'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/os2intra/settings'] = array(
    'title' => 'OS2Intra Settings',
    'description' => 'General settings for the OS2Intra project',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2intra_settings_settings_form'),
    'access arguments' => array('administer os2intra'),
    'type' => MENU_NORMAL_ITEM | MENU_DEFAULT_LOCAL_TASK,
    'file' => 'os2intra_settings.admin.inc',
  );
  return $items;
}
