<?php

/*
 * Search for value in multi-dimensional array
 */
function in_array_recursive($needle, $haystack, $strict = FALSE) {
  foreach ($haystack as $item) {
    if (($strict ? $item === $needle : $item == $needle) || (is_array($item) && in_array_recursive($needle, $item, $strict))) {
      return true;
    }
  }

  return false;
}

/*
 * Get top level taxonomy term
 */
function taxonomy_term_top_level_load($tid) {
  $taxonomy_term_parents = taxonomy_get_parents_all($tid);
  $taxonomy_term_top_level = NULL;

  // Run through all parents
  foreach($taxonomy_term_parents as $taxonomy_term_parent) {
    $taxonomy_term_parent_parents = taxonomy_get_parents_all($taxonomy_term_parent->tid);

    if ($taxonomy_term_parent_parents != false) {
      $taxonomy_term_top_level = $taxonomy_term_parent;
    }
  }

  return $taxonomy_term_top_level;
}
